from .lims_autosamplerMethod_query import lims_autosamplerMethod_query
from SBaaS_base.sbaas_template_io import sbaas_template_io

class lims_autosamplerMethod_io(lims_autosamplerMethod_query,sbaas_template_io):
    pass;